# This is a basic workflow to help you get started with Actions

name: CI

on:
  schedule:
    - cron: "0 4 * * *"
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: wget
      uses: wei/wget@v1
      with:
        args: -O api/players.xml https://s166-en.ogame.gameforge.com/api/players.xml

    - name: wget
        uses: wei/wget@v1
        with:
          args: -O api/planets.xml https://s166-en.ogame.gameforge.com/api/planets.xml
        
    - name: Deploy
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: gh-pages
        build_dir: public
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
